[project]
name = "client"
version = "0.1.0"
description = "The client provides a user-facing interface for interactive chat."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.39.0",
    "pydantic-settings>=2.10.1",
    "requests>=2.32.4",
]
